### ISSUE TITLE
How to work have "_"

### ISSUE THREAD

**Issue by juwen** [matthijsgroen/ebnf2railroad#25]
How to work like that:
class_modifier = "new"
				|"public"
				|"protected"
				|"internal"
				|"private"
				|"abstract"
				|"sealed"
				|"static"
				|"unsafe"
				;
have "_".

**Comment by matthijsgroen** [comment]
Normally you only use letters and numbers, and seperate words using a space. in your example:

```
class modifier = "new"
  | "public"
  | "protected"
  | "internal"
  | "private"
  | "abstract"
  | "sealed"
  | "static"
  | "unsafe"
  ;
```

**Comment by matthijsgroen** [comment]
So far I'm not able to see in the spec if an `_` is allowed in the identifier name. Are you aware of such a spec?
