### ISSUE TITLE
Railroad for '{ }' repetition-symbol is wrong.

### ISSUE THREAD

**Issue by pyjamads** [matthijsgroen/ebnf2railroad#27]
Railroad for '{ }' repetition-symbol is wrong.
The railroad diagram should show items repeated 1 or more times.
The railroad diagram currently shows items repeated 0 or more times.

**_Current railroad, and code._**
![image](https://user-images.githubusercontent.com/1052595/68487035-a22a4e00-0242-11ea-9038-daeb16b5052e.png)

**_Correct railroad, with hack code._**
![image](https://user-images.githubusercontent.com/1052595/68486647-d2bdb800-0241-11ea-96b2-31c505335ae6.png)

**The correct way to produce 0 or more railroad would be:
grammar = [ {rule} ] ;**

**_instead the above produces, extra skip lines:_**
![image](https://user-images.githubusercontent.com/1052595/68486975-89219d00-0242-11ea-9a7f-2ef0627886db.png)

**Comment by matthijsgroen** [comment]
The repetition `{ }` is actually *zero* or more:

From [Wikipedia](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form):

> Expressions that may be omitted or repeated can be represented through curly braces { ... }:

**Comment by matthijsgroen** [comment]
I agree about the extra skip lines, those could be omitted
