### ISSUE TITLE
How to collapse verbose EBNF into a single diagram?

### ISSUE THREAD

**Issue by agladysh** [matthijsgroen/ebnf2railroad#31]
I have a very verbose EBNF with a lot of redundant non-terminal symbols.

Right now the documentation I get mirrors the ebnf structure, documenting every non-terminal.

I would hesitate to collapse the symbols in the source EBNF, as it will affect the readability of the text. However, the small diagrams are not useful.

Is there a way to collapse **all** non-terminals to get a **single** railroad diagram? 

Ideally I would like to control the verbosity somehow, probably by explicitly marking non-terminals that I want to remain, and collapsing all others...

I see the structure-optimizer in the code, but it seems not to go this far...

I can provide a minimal example if it would help. Alternatively, I might code a PR, if you guide me in the right direction.

**Comment by matthijsgroen** [comment]
Yes that would be interesting.

The first problem is the system is currently "guessing" what the root node is. It is not sure of it. and a EBNF definition could have multiple roots as well.

The second problem is that EBNF allows for recursion.

We could try out something with `--nesting-level=4` for example.

**Comment by matthijsgroen** [comment]
I've been giving it more thought. I think it is possible, but will require the following steps in implementation:

1. If a production has a choice on root level, only containing terminals, mark it as "character set".
2. If a production has a choice on root level, only containing terminals or "character set", mark it as "character set".
3. Group all "character sets" at the bottom of the table of contents
4. Create an overview railroad for each "root" element. Each terminal will be expanded, surrounded by a dotted box indicating the name of that terminal.
5. When recursion happens, only show the collapsed terminal when first recurring hit happens
6. Keep "character sets" collapsed by default.

**Comment by matthijsgroen** [comment]
There are some other features I want to wrap up first, then I will start on this one :-)

**Comment by matthijsgroen** [comment]
![image](https://user-images.githubusercontent.com/23627/94059860-57c2a900-fde3-11ea-99f2-99131d69d628.png)

Do you mean something like this?
