### ISSUE TITLE
Does not support one-or-more operator

### ISSUE THREAD

**Issue by tragle** [matthijsgroen/ebnf2railroad#54]
Would be great to support the "one or more" syntax. I see this was requested in #27.

The spec includes syntax for this: see section section 5.8 of [ISO/IEC 14977](https://www.cl.cam.ac.uk/~mgk25/iso-14977.pdf) and [this StackOverflow question](https://stackoverflow.com/questions/55629053/how-to-denote-at-least-one-repetition-in-ebnf).

The syntax for one-or-more is a minus sign following a repitition group:

```ebnf
production = { nonterminal }-;
```

Currently ebnf2railroad throws a syntax error if you put a minus-sign after a repetition group.

**Comment by matthijsgroen** [comment]
Ah I was not aware of this syntax. Nice! I hope to add this soon™
